export const names = [
  'motherboards',
  'rams',
  'cpus',
  'gpus',
  'internal-drives',
  'power-supplies',
  'cases',
  'mobiles',
  'laptops',
];
export const CPUFormData = {
    name: '',
    price: '',
    status: true,
    base_clock: 0,
    turbo_clock: 0,
    cores: 0,
    threads: 0,
    socket: '',
    tdp: 0,
    producer: 0,
    integrated_graphics: '',
    external_image: '',
    image: null,
  };
  export const GPUFormData = {
    name: '',
    price: '',
    pci_e: 0,
    vram: 0 , 
    status: true,
    boost_clock: 0,
    memory_clock: 0,
    length: 0.0,
    slots: 0.0,
    connectors_8pin: 0,
    connectors_6pin: 0,
    hdmi: 0,
    display_port: 0,
    dvi: 0,
    vga: 0,
    cores: 0,
    tdp: 0,
    series: 0, 
    producer: 0, 
    sync: 0 ,
    external_image: '',
    image: null,
  }
  export const MotherBoardsFormData = {
    name: '',
    price: '',
    memory_max_capacity: 0,
    status:true,
    ram_slots: 0,
    m2_pci_e_3: 0,
    m2_pci_e_4: 0,
    usb_3_slots: 0,
    usb_3_headers: 0,
    usb_3_type_c: 0,
    vga: 0,
    dvi: 0,
    display_port: 0,
    hdmi: 0,
    pci_e_3: 0,
    pci_e_4: 0,
    form_factor: 0, 
    socket: 0, 
    ram_type: 0,
    chipset: 0, 
    producer: 0, 
    external_image: '',
    image: null,
  };
  export const RAMFormData ={
    name: '',
    price: '',
    status: true,
    size: 0,
    clock: 0,
    sticks: 0,
    timings: '',
    type: 0,
    producer: 0,
    external_image: '',
    image: null,
      
  }
export const CaseFormData={
    name: '',
    price: '',
    status: true,
    type: 0,
    color: 0,
    side_panel:0,
    style:0,
    external_image: '', 
    image:null,
}
export const InternalDriveFormData={
    name: '',
    price: '',
    status: true,
    capacity: 0,
    price_per_gb: '',
    cache: 0,
    form_factor: '',
    interface: '',
    drive_type: 0,
    external_image: '',
    image: null,
}
export const PowerSupplyFormData={
    name: '',
    price: '',
    status: true,
    wattage: 0,
    type: 0,
    efficiency:0,
    external_image: '',
    image: null,
}
export const LaptopFormData={
    name: '',
    price: ' ',
    status: true,
    screen_size: 0,
    cpu_type: '',
    memory: 0,
    storage: '',
    gpu: '',
    vram: 0,
    gpu_speed: 0,
    gpu_cores: 0,
    resolution: '',
    weight: 0,
    backlit_keyboard: false,
    touchscreen: false,
    cpu_speed: 0,
    number_of_cores: '',
    display_type: '',
    graphic_type: '',
    operating_system: '',
    webcam: true,
    external_image: '',
    image: null
}
export const MobileFormData ={
    name: '',
    price: '',
    status: true,
    cameras: '',
    cpu: '',
    core_count: 0,
    cpu_speed: 0.0,
    storage: '',
    ram: 0,
    screen_size: 0.0,
    refresh_rate: 0,
    battery: 0,
    fast_charging: false,
    main_camera: 0,
    front_camera: 0,
    cameras_num: 0,
    external_image: '',
    image: null
}